//* Login
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LIMPIAR_USER = 'LIMPIAR_USER'

//*Anuncios
export const GET_ANUNCIOS = 'GET_ANUNCIOS'
export const GET_ANUNCIO_UNICA = 'GET_ANUNCIO_UNICA'
export const LIMPIAR_ANUNCIO = 'LIMPIAR_ANUNCIO'
export const ERROR_ANUNCIO = 'ERROR_ANUNCIO'
export const AGREGAR_ANUNCIO = 'AGREGAR_ANUNCIO' 
export const ELIMINAR_PUBLICACION = 'ELIMINAR_PUBLICACION'
export const GET_ANUNCIOS_MATERIA = 'GET_ANUNCIOS_MATERIA'
export const LIMPIAR_ANUNCIOS_MATERIA = 'LIMPIAR_ANUNCIOS_MATERIA'
export const AGREGAR_ANUNCIO_MATERIA = 'AGREGAR_ANUNCIO_MATERIA' 

//*Comentarios
export const GET_COMENTARIOS = 'GET_COMENTARIOS'
export const AGREGAR_COMENTARIO = 'AGREGAR_COMENTARIO'
export const ELIMINAR_COMENTARIO = 'ELIMINAR_COMENTARIO'
export const LIMPIAR_COMENTARIOS = 'LIMPIAR_COMENTARIOS'
export const ERROR_COMENTARIOS = 'ERROR_COMENTARIOS'

//*Lista de alumnos
export const GET_ALUMNOS = 'GET_ALUMNOS'
export const GET_ALUMNO_UNICO = 'GET_ALUMNO_UNICO'
export const AGREGAR_ALUMNO = 'AGREGAR_ALUMNO'
export const EDITAR_ALUMNO = 'EDITAR_ALUMNO'
export const ELIMINAR_ALUMNO = 'ELIMINAR_ALUMNO'
export const LIMPIAR_ALUMNO = 'LIMPIAR_ALUMNO'
export const ERROR_ALUMNO = 'ERROR_ALUMNO'

//*Materias
export const GET_MATERIAS = 'GET_MATERIAS'
export const GET_MATERIA_UNICA = 'GET_MATERIA_UNICA'
export const AGREGAR_MATERIA = 'AGREGAR_MATERIA'
export const EDITAR_MATERIA = 'EDITAR_MATERIA'
export const ELIMINAR_MATERIA = 'ELIMINAR_MATERIA'
export const LIMPIAR_MATERIA = 'LIMPIAR_MATERIA'
export const ERROR_MATERIA = 'ERROR_MATERIA'

//*Notas
export const AGREGAR_NOTA = 'AGREGAR_NOTA'
export const EDITAR_NOTA = 'ELIMINAR_NOTA'
export const LIMPIAR_NOTA = 'LIMPIAR_NOTA'
export const ERROR_NOTA = 'ERROR_NOTA'
